#
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "lastname" : "coco",
    "firstname" : "coco",
    "phone" : "0140161716",
    "address" : "8 rue de romainville",
    "city" : "paris",
    "country" : "france",
    "email" : "moussiamottal@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN"
}

### FAUX PASS
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### FAUX MAIL
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamsottal@gmail.com",
    "password" : "coco"
}


### FAUX TOUT
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamodgbusjkgdbttal@gmail.com",
    "password" : "bla"
}

### 
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### 
GET http://localhost:3003/user/current


### 
DELETE http://localhost:3003/session