#
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "lastname" : "admin",
    "firstname" : "admin",
    "phone" : "0140161716",
    "address" : "8 rue de romainville",
    "city" : "paris",
    "country" : "france",
    "email" : "kejlerj@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN"
}

### CREATE PRO
POST http://localhost:3003/user/pro/create
Content-Type: application/json

{
    "lastname" : "coco",
    "firstname" : "coco",
    "phone" : "0140161716",
    "address" : "8 rue de romainville",
    "city" : "paris",
    "country" : "france",
    "email" : "moussiamottal@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN",
    "role" : "PRO",
    "job": "pediatre"
}

### FAUX PASS
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### FAUX MAIL
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamsottal@gmail.com",
    "password" : "coco"
}


### FAUX TOUT
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamodgbusjkgdbttal@gmail.com",
    "password" : "bla"
}

### 
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### 
GET http://localhost:3003/user/current



### CONNEXION ADMIN
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "sosparentsoff@gmail.com",
    "password" : "Hayamottal555/"
}

### 
GET http://localhost:3003/admin/pro


### GET PRO Moussiamottal@gmail.com
GET http://localhost:3003/admin/pro/628be114daaf25d16d391487
content-type: application/json


### GET PARENT kejlerj@gmail.com
GET http://localhost:3003/admin/parent/628be155fe616596c4795e3e


content-type: application/json
### SUPPRIMER UN PRO moussiamottal@gmail.com
DELETE http://localhost:3003/admin/628be114daaf25d16d391487


### SUPPRIMER UN PARENT kejlerj@gmail.com
DELETE http://localhost:3003/admin/628be155fe616596c4795e3e


### 
GET http://localhost:3003/admin/parent


###
PUT http://localhost:8000/admin/628be114daaf25d16d391487
content-type: application/json
{
    "activatedByAdmin": false
}

### 
DELETE http://localhost:3003/session