export const strings = {
    VALIDATE_EMAIL_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_MAIL: 'Saisie incorrect.',
    VALIDATE_INVALID_MAIL: 'Email invalide.',
    VALIDATE_PASSWORD_NEEDED: 'Champ obligatoire.',
    VALIDATE_WEAK_PASSWORD: 'Mot de passe trop faible.',
    VALIDATE_FIRSTNAME_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_FIRSTNAME: 'Champ obligatoire.',
    VALIDATE_LASTNAME_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_LASTNAME: 'Saisie incorrect.',
    INVALID_CREDS: 'Identifiants invalide.',
    VALIDATE_PHONE_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_PHONE: 'Champ vide.',
    VALIDATE_ADDRESS_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_ADDRESS: 'Champ vide.',
    VALIDATE_CITY_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_CITY: 'Champ vide.',
    VALIDATE_ZIPCODE_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_ZIPCODE: 'Champ vide.',
    VALIDATE_SEX_NEEDED: 'Champ obligatoire.',
    VALIDATE_EMPTY_SEX: 'Champ vide.',
    VALIDATE_ERROR_ZIPCODE: 'Zip Code non valide.',
    VALIDATE_ERROR_PHONE: 'Téléphone non valide.'
}